export const payments = [
  {
    name: "Abdulrahman Saad",
    email: "abdulrahman.saad2303@gmail.com",
    status: "Success",
    amount: "250.00",
  },
  {
    name: "Ahmed Mansour",
    email: "ahmed.m@company.com",
    status: "Pending",
    amount: "120.50",
  },
  {
    name: "Sara El-Sayed",
    email: "sara.design@freelance.io",
    status: "Failed",
    amount: "450.00",
  },
  {
    name: "Mona Hassan",
    email: "mona.h@tech.net",
    status: "Success",
    amount: "89.99",
  },
  {
    name: "Omar Khaled",
    email: "omar.k@startup.com",
    status: "Success",
    amount: "1,200.00",
  },
  {
    name: "Hassan Ali",
    email: "hassan.ali@gmail.com",
    status: "Pending",
    amount: "300.25",
  },
  {
    name: "Layla Mahmoud",
    email: "layla.m@agency.org",
    status: "Success",
    amount: "55.00",
  },
  {
    name: "Youssef Ibrahim",
    email: "youssef.i@dev.io",
    status: "Failed",
    amount: "210.00",
  },
  {
    name: "Nour El-Din",
    email: "nour.e@cloud.com",
    status: "Success",
    amount: "750.40",
  },
  {
    name: "Mariam Fawzy",
    email: "mariam.f@marketing.co",
    status: "Success",
    amount: "140.00",
  },
  {
    name: "Ziad Tarek",
    email: "ziad.t@gaming.net",
    status: "Pending",
    amount: "25.00",
  },
  {
    name: "Dina Samy",
    email: "dina.s@education.edu",
    status: "Success",
    amount: "400.00",
  },
  {
    name: "Kareem Adel",
    email: "kareem.a@logistics.com",
    status: "Success",
    amount: "670.00",
  },
  {
    name: "Hoda Ahmed",
    status: "Failed",
    email: "hoda.a@art.io",
    amount: "15.50",
  },
  {
    name: "Mostafa Bakr",
    email: "mostafa.b@fintech.com",
    status: "Success",
    amount: "990.00",
  },
  {
    name: "Rania Emad",
    email: "rania.e@health.org",
    status: "Pending",
    amount: "110.00",
  },
  {
    name: "Tamer Hosny",
    email: "tamer.h@media.com",
    status: "Success",
    amount: "320.00",
  },
  {
    name: "Basma Soliman",
    email: "basma.s@retail.com",
    status: "Success",
    amount: "45.90",
  },
  {
    name: "Waleed Refaat",
    email: "waleed.r@construction.biz",
    status: "Failed",
    amount: "2,500.00",
  },
  {
    name: "Aya Gamal",
    email: "aya.g@fashion.net",
    status: "Success",
    amount: "180.00",
  },
  {
    name: "Sherif Amer",
    email: "sherif.a@consultancy.com",
    status: "Success",
    amount: "500.00",
  },
  {
    name: "Nadine Wael",
    email: "nadine.w@hr.io",
    status: "Pending",
    amount: "200.00",
  },
  {
    name: "Ehab Galal",
    email: "ehab.g@sport.com",
    status: "Success",
    amount: "350.00",
  },
  {
    name: "Salma Magdy",
    email: "salma.m@travel.co",
    status: "Success",
    amount: "1,100.00",
  },
  {
    name: "Fady Aziz",
    email: "fady.a@legal.net",
    status: "Failed",
    amount: "90.00",
  },
  {
    name: "Ghada Adel",
    email: "ghada.a@cinema.com",
    status: "Success",
    amount: "60.00",
  },
  {
    name: "Hany Ramzy",
    email: "hany.r@comedy.io",
    status: "Success",
    amount: "125.00",
  },
  {
    name: "Jana Amr",
    email: "jana.a@kids.com",
    status: "Pending",
    amount: "40.00",
  },
  {
    name: "Khaled Selim",
    email: "khaled.s@music.net",
    status: "Success",
    amount: "800.00",
  },
  {
    name: "Amira Said",
    email: "amira.s@luxury.org",
    status: "Success",
    amount: "3,000.00",
  },
];

export const users = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    role: "Admin",
    status: "Active",
    joined: "2024-01-12",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
  },
  {
    id: "2",
    name: "Sarah Smith",
    email: "sarah.s@tech.com",
    role: "Editor",
    status: "Active",
    joined: "2024-02-05",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
  },
  {
    id: "3",
    name: "Michael Chen",
    email: "m.chen@dev.io",
    role: "Moderator",
    status: "Pending",
    joined: "2024-02-15",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
  },
  {
    id: "4",
    name: "Aisha Hassan",
    email: "aisha.h@design.net",
    role: "User",
    status: "Active",
    joined: "2024-03-01",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha",
  },
  {
    id: "5",
    name: "Omar Khaled",
    email: "omar.k@startup.com",
    role: "User",
    status: "Inactive",
    joined: "2023-11-20",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Omar",
  },
  {
    id: "6",
    name: "Elena Rodriguez",
    email: "elena.ro@global.org",
    role: "Moderator",
    status: "Active",
    joined: "2024-01-30",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elena",
  },
];
